# .prettierrc.yml
experimentalTernaries: true
jsxSingleQuote: true
printWidth: 100
semi: false
singleQuote: true
tabWidth: 2
trailingComma: all

tailwindFunctions: [clsx]
plugins: [prettier-plugin-tailwindcss]
