# .prettierrc.yml
experimentalTernaries: true
printWidth: 80
semi: false
singleQuote: true
jsxSingleQuote: true
singleAttributePerLine: true
tabWidth: 2
trailingComma: all

tailwindFunctions: [clsx]
plugins: [prettier-plugin-tailwindcss]
